---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-cluster
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./eksd-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-k8s-platform-gitrepo
  validation: client
