---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops-runtime/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-k8s-platform-gitrepo
  validation: client
